// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/gostatsd.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventV2_EventPriority int32

const (
	EventV2_Normal EventV2_EventPriority = 0
	EventV2_Low    EventV2_EventPriority = 1
)

var EventV2_EventPriority_name = map[int32]string{
	0: "Normal",
	1: "Low",
}
var EventV2_EventPriority_value = map[string]int32{
	"Normal": 0,
	"Low":    1,
}

func (x EventV2_EventPriority) String() string {
	return proto.EnumName(EventV2_EventPriority_name, int32(x))
}
func (EventV2_EventPriority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{9, 0}
}

type EventV2_AlertType int32

const (
	EventV2_Info    EventV2_AlertType = 0
	EventV2_Warning EventV2_AlertType = 1
	EventV2_Error   EventV2_AlertType = 2
	EventV2_Success EventV2_AlertType = 3
)

var EventV2_AlertType_name = map[int32]string{
	0: "Info",
	1: "Warning",
	2: "Error",
	3: "Success",
}
var EventV2_AlertType_value = map[string]int32{
	"Info":    0,
	"Warning": 1,
	"Error":   2,
	"Success": 3,
}

func (x EventV2_AlertType) String() string {
	return proto.EnumName(EventV2_AlertType_name, int32(x))
}
func (EventV2_AlertType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{9, 1}
}

type RawMessageV2 struct {
	Counters             map[string]*CounterTagV2 `protobuf:"bytes,1,rep,name=Counters,proto3" json:"Counters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Gauges               map[string]*GaugeTagV2   `protobuf:"bytes,2,rep,name=Gauges,proto3" json:"Gauges,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sets                 map[string]*SetTagV2     `protobuf:"bytes,3,rep,name=Sets,proto3" json:"Sets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timers               map[string]*TimerTagV2   `protobuf:"bytes,4,rep,name=Timers,proto3" json:"Timers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RawMessageV2) Reset()         { *m = RawMessageV2{} }
func (m *RawMessageV2) String() string { return proto.CompactTextString(m) }
func (*RawMessageV2) ProtoMessage()    {}
func (*RawMessageV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{0}
}
func (m *RawMessageV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMessageV2.Unmarshal(m, b)
}
func (m *RawMessageV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMessageV2.Marshal(b, m, deterministic)
}
func (dst *RawMessageV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMessageV2.Merge(dst, src)
}
func (m *RawMessageV2) XXX_Size() int {
	return xxx_messageInfo_RawMessageV2.Size(m)
}
func (m *RawMessageV2) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMessageV2.DiscardUnknown(m)
}

var xxx_messageInfo_RawMessageV2 proto.InternalMessageInfo

func (m *RawMessageV2) GetCounters() map[string]*CounterTagV2 {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *RawMessageV2) GetGauges() map[string]*GaugeTagV2 {
	if m != nil {
		return m.Gauges
	}
	return nil
}

func (m *RawMessageV2) GetSets() map[string]*SetTagV2 {
	if m != nil {
		return m.Sets
	}
	return nil
}

func (m *RawMessageV2) GetTimers() map[string]*TimerTagV2 {
	if m != nil {
		return m.Timers
	}
	return nil
}

type CounterTagV2 struct {
	TagMap               map[string]*RawCounterV2 `protobuf:"bytes,1,rep,name=TagMap,proto3" json:"TagMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CounterTagV2) Reset()         { *m = CounterTagV2{} }
func (m *CounterTagV2) String() string { return proto.CompactTextString(m) }
func (*CounterTagV2) ProtoMessage()    {}
func (*CounterTagV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{1}
}
func (m *CounterTagV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterTagV2.Unmarshal(m, b)
}
func (m *CounterTagV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterTagV2.Marshal(b, m, deterministic)
}
func (dst *CounterTagV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterTagV2.Merge(dst, src)
}
func (m *CounterTagV2) XXX_Size() int {
	return xxx_messageInfo_CounterTagV2.Size(m)
}
func (m *CounterTagV2) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterTagV2.DiscardUnknown(m)
}

var xxx_messageInfo_CounterTagV2 proto.InternalMessageInfo

func (m *CounterTagV2) GetTagMap() map[string]*RawCounterV2 {
	if m != nil {
		return m.TagMap
	}
	return nil
}

type GaugeTagV2 struct {
	TagMap               map[string]*RawGaugeV2 `protobuf:"bytes,1,rep,name=TagMap,proto3" json:"TagMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GaugeTagV2) Reset()         { *m = GaugeTagV2{} }
func (m *GaugeTagV2) String() string { return proto.CompactTextString(m) }
func (*GaugeTagV2) ProtoMessage()    {}
func (*GaugeTagV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{2}
}
func (m *GaugeTagV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GaugeTagV2.Unmarshal(m, b)
}
func (m *GaugeTagV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GaugeTagV2.Marshal(b, m, deterministic)
}
func (dst *GaugeTagV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GaugeTagV2.Merge(dst, src)
}
func (m *GaugeTagV2) XXX_Size() int {
	return xxx_messageInfo_GaugeTagV2.Size(m)
}
func (m *GaugeTagV2) XXX_DiscardUnknown() {
	xxx_messageInfo_GaugeTagV2.DiscardUnknown(m)
}

var xxx_messageInfo_GaugeTagV2 proto.InternalMessageInfo

func (m *GaugeTagV2) GetTagMap() map[string]*RawGaugeV2 {
	if m != nil {
		return m.TagMap
	}
	return nil
}

type SetTagV2 struct {
	TagMap               map[string]*RawSetV2 `protobuf:"bytes,1,rep,name=TagMap,proto3" json:"TagMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetTagV2) Reset()         { *m = SetTagV2{} }
func (m *SetTagV2) String() string { return proto.CompactTextString(m) }
func (*SetTagV2) ProtoMessage()    {}
func (*SetTagV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{3}
}
func (m *SetTagV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTagV2.Unmarshal(m, b)
}
func (m *SetTagV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTagV2.Marshal(b, m, deterministic)
}
func (dst *SetTagV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTagV2.Merge(dst, src)
}
func (m *SetTagV2) XXX_Size() int {
	return xxx_messageInfo_SetTagV2.Size(m)
}
func (m *SetTagV2) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTagV2.DiscardUnknown(m)
}

var xxx_messageInfo_SetTagV2 proto.InternalMessageInfo

func (m *SetTagV2) GetTagMap() map[string]*RawSetV2 {
	if m != nil {
		return m.TagMap
	}
	return nil
}

type TimerTagV2 struct {
	TagMap               map[string]*RawTimerV2 `protobuf:"bytes,1,rep,name=TagMap,proto3" json:"TagMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TimerTagV2) Reset()         { *m = TimerTagV2{} }
func (m *TimerTagV2) String() string { return proto.CompactTextString(m) }
func (*TimerTagV2) ProtoMessage()    {}
func (*TimerTagV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{4}
}
func (m *TimerTagV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerTagV2.Unmarshal(m, b)
}
func (m *TimerTagV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerTagV2.Marshal(b, m, deterministic)
}
func (dst *TimerTagV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerTagV2.Merge(dst, src)
}
func (m *TimerTagV2) XXX_Size() int {
	return xxx_messageInfo_TimerTagV2.Size(m)
}
func (m *TimerTagV2) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerTagV2.DiscardUnknown(m)
}

var xxx_messageInfo_TimerTagV2 proto.InternalMessageInfo

func (m *TimerTagV2) GetTagMap() map[string]*RawTimerV2 {
	if m != nil {
		return m.TagMap
	}
	return nil
}

type RawCounterV2 struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawCounterV2) Reset()         { *m = RawCounterV2{} }
func (m *RawCounterV2) String() string { return proto.CompactTextString(m) }
func (*RawCounterV2) ProtoMessage()    {}
func (*RawCounterV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{5}
}
func (m *RawCounterV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawCounterV2.Unmarshal(m, b)
}
func (m *RawCounterV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawCounterV2.Marshal(b, m, deterministic)
}
func (dst *RawCounterV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawCounterV2.Merge(dst, src)
}
func (m *RawCounterV2) XXX_Size() int {
	return xxx_messageInfo_RawCounterV2.Size(m)
}
func (m *RawCounterV2) XXX_DiscardUnknown() {
	xxx_messageInfo_RawCounterV2.DiscardUnknown(m)
}

var xxx_messageInfo_RawCounterV2 proto.InternalMessageInfo

func (m *RawCounterV2) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RawCounterV2) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RawCounterV2) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RawGaugeV2 struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGaugeV2) Reset()         { *m = RawGaugeV2{} }
func (m *RawGaugeV2) String() string { return proto.CompactTextString(m) }
func (*RawGaugeV2) ProtoMessage()    {}
func (*RawGaugeV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{6}
}
func (m *RawGaugeV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGaugeV2.Unmarshal(m, b)
}
func (m *RawGaugeV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGaugeV2.Marshal(b, m, deterministic)
}
func (dst *RawGaugeV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGaugeV2.Merge(dst, src)
}
func (m *RawGaugeV2) XXX_Size() int {
	return xxx_messageInfo_RawGaugeV2.Size(m)
}
func (m *RawGaugeV2) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGaugeV2.DiscardUnknown(m)
}

var xxx_messageInfo_RawGaugeV2 proto.InternalMessageInfo

func (m *RawGaugeV2) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RawGaugeV2) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RawGaugeV2) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RawSetV2 struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawSetV2) Reset()         { *m = RawSetV2{} }
func (m *RawSetV2) String() string { return proto.CompactTextString(m) }
func (*RawSetV2) ProtoMessage()    {}
func (*RawSetV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{7}
}
func (m *RawSetV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawSetV2.Unmarshal(m, b)
}
func (m *RawSetV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawSetV2.Marshal(b, m, deterministic)
}
func (dst *RawSetV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawSetV2.Merge(dst, src)
}
func (m *RawSetV2) XXX_Size() int {
	return xxx_messageInfo_RawSetV2.Size(m)
}
func (m *RawSetV2) XXX_DiscardUnknown() {
	xxx_messageInfo_RawSetV2.DiscardUnknown(m)
}

var xxx_messageInfo_RawSetV2 proto.InternalMessageInfo

func (m *RawSetV2) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RawSetV2) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RawSetV2) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type RawTimerV2 struct {
	Tags                 []string  `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Hostname             string    `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	SampleCount          float64   `protobuf:"fixed64,3,opt,name=SampleCount,proto3" json:"SampleCount,omitempty"`
	Values               []float64 `protobuf:"fixed64,4,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RawTimerV2) Reset()         { *m = RawTimerV2{} }
func (m *RawTimerV2) String() string { return proto.CompactTextString(m) }
func (*RawTimerV2) ProtoMessage()    {}
func (*RawTimerV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{8}
}
func (m *RawTimerV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTimerV2.Unmarshal(m, b)
}
func (m *RawTimerV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTimerV2.Marshal(b, m, deterministic)
}
func (dst *RawTimerV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTimerV2.Merge(dst, src)
}
func (m *RawTimerV2) XXX_Size() int {
	return xxx_messageInfo_RawTimerV2.Size(m)
}
func (m *RawTimerV2) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTimerV2.DiscardUnknown(m)
}

var xxx_messageInfo_RawTimerV2 proto.InternalMessageInfo

func (m *RawTimerV2) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RawTimerV2) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RawTimerV2) GetSampleCount() float64 {
	if m != nil {
		return m.SampleCount
	}
	return 0
}

func (m *RawTimerV2) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type EventV2 struct {
	Title                string                `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Text                 string                `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	DateHappened         int64                 `protobuf:"varint,3,opt,name=DateHappened,proto3" json:"DateHappened,omitempty"`
	Hostname             string                `protobuf:"bytes,4,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	AggregationKey       string                `protobuf:"bytes,5,opt,name=AggregationKey,proto3" json:"AggregationKey,omitempty"`
	SourceTypeName       string                `protobuf:"bytes,6,opt,name=SourceTypeName,proto3" json:"SourceTypeName,omitempty"`
	Tags                 []string              `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty"`
	SourceIP             string                `protobuf:"bytes,8,opt,name=SourceIP,proto3" json:"SourceIP,omitempty"`
	Priority             EventV2_EventPriority `protobuf:"varint,9,opt,name=Priority,proto3,enum=pb.EventV2_EventPriority" json:"Priority,omitempty"`
	Type                 EventV2_AlertType     `protobuf:"varint,10,opt,name=Type,proto3,enum=pb.EventV2_AlertType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventV2) Reset()         { *m = EventV2{} }
func (m *EventV2) String() string { return proto.CompactTextString(m) }
func (*EventV2) ProtoMessage()    {}
func (*EventV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_gostatsd_02649f73f2826ea1, []int{9}
}
func (m *EventV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventV2.Unmarshal(m, b)
}
func (m *EventV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventV2.Marshal(b, m, deterministic)
}
func (dst *EventV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventV2.Merge(dst, src)
}
func (m *EventV2) XXX_Size() int {
	return xxx_messageInfo_EventV2.Size(m)
}
func (m *EventV2) XXX_DiscardUnknown() {
	xxx_messageInfo_EventV2.DiscardUnknown(m)
}

var xxx_messageInfo_EventV2 proto.InternalMessageInfo

func (m *EventV2) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EventV2) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EventV2) GetDateHappened() int64 {
	if m != nil {
		return m.DateHappened
	}
	return 0
}

func (m *EventV2) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *EventV2) GetAggregationKey() string {
	if m != nil {
		return m.AggregationKey
	}
	return ""
}

func (m *EventV2) GetSourceTypeName() string {
	if m != nil {
		return m.SourceTypeName
	}
	return ""
}

func (m *EventV2) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *EventV2) GetSourceIP() string {
	if m != nil {
		return m.SourceIP
	}
	return ""
}

func (m *EventV2) GetPriority() EventV2_EventPriority {
	if m != nil {
		return m.Priority
	}
	return EventV2_Normal
}

func (m *EventV2) GetType() EventV2_AlertType {
	if m != nil {
		return m.Type
	}
	return EventV2_Info
}

func init() {
	proto.RegisterType((*RawMessageV2)(nil), "pb.RawMessageV2")
	proto.RegisterMapType((map[string]*CounterTagV2)(nil), "pb.RawMessageV2.CountersEntry")
	proto.RegisterMapType((map[string]*GaugeTagV2)(nil), "pb.RawMessageV2.GaugesEntry")
	proto.RegisterMapType((map[string]*SetTagV2)(nil), "pb.RawMessageV2.SetsEntry")
	proto.RegisterMapType((map[string]*TimerTagV2)(nil), "pb.RawMessageV2.TimersEntry")
	proto.RegisterType((*CounterTagV2)(nil), "pb.CounterTagV2")
	proto.RegisterMapType((map[string]*RawCounterV2)(nil), "pb.CounterTagV2.TagMapEntry")
	proto.RegisterType((*GaugeTagV2)(nil), "pb.GaugeTagV2")
	proto.RegisterMapType((map[string]*RawGaugeV2)(nil), "pb.GaugeTagV2.TagMapEntry")
	proto.RegisterType((*SetTagV2)(nil), "pb.SetTagV2")
	proto.RegisterMapType((map[string]*RawSetV2)(nil), "pb.SetTagV2.TagMapEntry")
	proto.RegisterType((*TimerTagV2)(nil), "pb.TimerTagV2")
	proto.RegisterMapType((map[string]*RawTimerV2)(nil), "pb.TimerTagV2.TagMapEntry")
	proto.RegisterType((*RawCounterV2)(nil), "pb.RawCounterV2")
	proto.RegisterType((*RawGaugeV2)(nil), "pb.RawGaugeV2")
	proto.RegisterType((*RawSetV2)(nil), "pb.RawSetV2")
	proto.RegisterType((*RawTimerV2)(nil), "pb.RawTimerV2")
	proto.RegisterType((*EventV2)(nil), "pb.EventV2")
	proto.RegisterEnum("pb.EventV2_EventPriority", EventV2_EventPriority_name, EventV2_EventPriority_value)
	proto.RegisterEnum("pb.EventV2_AlertType", EventV2_AlertType_name, EventV2_AlertType_value)
}

func init() { proto.RegisterFile("pb/gostatsd.proto", fileDescriptor_gostatsd_02649f73f2826ea1) }

var fileDescriptor_gostatsd_02649f73f2826ea1 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x9d, 0x9b, 0xb4, 0x4d, 0x6e, 0xbb, 0x29, 0x58, 0x03, 0x85, 0x6a, 0x42, 0x55, 0x34, 0x4d,
	0xe5, 0xa5, 0xa0, 0x02, 0x12, 0xda, 0xdb, 0x04, 0xd5, 0x56, 0x8d, 0x4d, 0x93, 0x5b, 0x8d, 0x67,
	0x77, 0x33, 0x51, 0x45, 0x9b, 0x44, 0x8e, 0xbb, 0xd2, 0x1f, 0xc0, 0x13, 0x4f, 0xf0, 0x67, 0xf8,
	0x7b, 0xc8, 0x76, 0x9a, 0xc6, 0x6d, 0xd0, 0x36, 0xc1, 0x53, 0x7d, 0x3f, 0xce, 0xb9, 0xc7, 0xe7,
	0x46, 0x2e, 0x3c, 0x49, 0xc6, 0xaf, 0xc2, 0x38, 0x15, 0x54, 0xa4, 0xb7, 0xdd, 0x84, 0xc7, 0x22,
	0xc6, 0x95, 0x64, 0x1c, 0xfc, 0xb2, 0xa1, 0x49, 0xe8, 0xe2, 0x82, 0xa5, 0x29, 0x0d, 0xd9, 0x75,
	0x0f, 0x1f, 0x83, 0xf3, 0x21, 0x9e, 0x47, 0x82, 0xf1, 0xd4, 0x47, 0x6d, 0xab, 0xd3, 0xe8, 0xbd,
	0xe8, 0x26, 0xe3, 0x6e, 0xb1, 0xa7, 0xbb, 0x6a, 0xe8, 0x47, 0x82, 0x2f, 0x49, 0xde, 0x8f, 0xdf,
	0x42, 0xed, 0x94, 0xce, 0x43, 0x96, 0xfa, 0x15, 0x85, 0x3c, 0xd8, 0x42, 0xea, 0xb2, 0xc6, 0x65,
	0xbd, 0xb8, 0x0b, 0xf6, 0x90, 0x89, 0xd4, 0xb7, 0x14, 0xa6, 0xb5, 0x85, 0x91, 0x45, 0x8d, 0x50,
	0x7d, 0x72, 0xca, 0x68, 0x32, 0x93, 0xfa, 0xec, 0xbf, 0x4c, 0xd1, 0xe5, 0x6c, 0x8a, 0x0e, 0x5a,
	0x17, 0xb0, 0x6b, 0xc8, 0xc6, 0x1e, 0x58, 0x5f, 0xd9, 0xd2, 0x47, 0x6d, 0xd4, 0x71, 0x89, 0x3c,
	0xe2, 0x23, 0xa8, 0xde, 0xd1, 0xe9, 0x9c, 0xf9, 0x95, 0x36, 0xea, 0x34, 0x7a, 0x9e, 0xe4, 0xcd,
	0x30, 0x23, 0x1a, 0x5e, 0xf7, 0x88, 0x2e, 0x1f, 0x57, 0xde, 0xa3, 0xd6, 0x00, 0x1a, 0x85, 0xbb,
	0x94, 0x90, 0x1d, 0x9a, 0x64, 0x7b, 0x92, 0x4c, 0x21, 0xb6, 0xa8, 0xfa, 0xe0, 0xe6, 0x57, 0x2c,
	0x21, 0x0a, 0x4c, 0xa2, 0xa6, 0x24, 0x1a, 0x32, 0x51, 0xa6, 0xa8, 0x70, 0xef, 0x07, 0x2a, 0x52,
	0x88, 0x4d, 0xaa, 0xe0, 0x27, 0x82, 0x66, 0xf1, 0xe2, 0xca, 0x72, 0x1a, 0x5e, 0xd0, 0x24, 0xfb,
	0x24, 0x0e, 0x36, 0xad, 0xe9, 0xea, 0xf2, 0xca, 0x72, 0x15, 0xb4, 0xce, 0xa1, 0x51, 0x48, 0x3f,
	0xd0, 0x70, 0x42, 0x17, 0x19, 0xb1, 0xa9, 0xe9, 0x07, 0x02, 0x58, 0xfb, 0x87, 0x7b, 0x1b, 0x8a,
	0x5a, 0xa6, 0xbf, 0xa5, 0x7a, 0x06, 0xf7, 0xe9, 0x29, 0x73, 0x88, 0xd0, 0x85, 0xa2, 0x35, 0xd5,
	0x7c, 0x47, 0xe0, 0xac, 0x96, 0x80, 0x5f, 0x6f, 0x68, 0xf1, 0x8b, 0x2b, 0x2a, 0x55, 0x72, 0x7a,
	0x9f, 0x92, 0xb2, 0xa5, 0x13, 0xba, 0x18, 0x32, 0xb1, 0xed, 0xca, 0x7a, 0x87, 0xe5, 0xae, 0xac,
	0xeb, 0xff, 0xd5, 0x15, 0x45, 0x6b, 0xaa, 0x19, 0xa9, 0xb7, 0x24, 0x5f, 0x1f, 0xc6, 0x60, 0x8f,
	0x68, 0xa8, 0xdf, 0x11, 0x97, 0xa8, 0x33, 0x6e, 0x81, 0x73, 0x16, 0xa7, 0x22, 0xa2, 0x33, 0x4d,
	0xe8, 0x92, 0x3c, 0xc6, 0xfb, 0x50, 0xbd, 0x56, 0x93, 0xac, 0x36, 0xea, 0x58, 0x44, 0x07, 0x01,
	0x01, 0x58, 0x2f, 0xe1, 0xdf, 0x38, 0xd1, 0x9a, 0xd3, 0x59, 0xd9, 0xf9, 0x68, 0xc6, 0x67, 0x50,
	0x53, 0x24, 0xfa, 0xc5, 0x72, 0x49, 0x16, 0x05, 0x77, 0x4a, 0x67, 0x66, 0xcb, 0xa3, 0x59, 0xdb,
	0xd0, 0x18, 0xd2, 0x59, 0x32, 0x65, 0xca, 0xbe, 0x4c, 0x6d, 0x31, 0x55, 0x98, 0x2b, 0xdf, 0x3d,
	0x94, 0xcf, 0xfd, 0x6d, 0x41, 0xbd, 0x7f, 0xc7, 0x22, 0x79, 0x97, 0x7d, 0xa8, 0x8e, 0x26, 0x62,
	0xca, 0xb2, 0xfd, 0xe9, 0x40, 0x69, 0x61, 0xdf, 0x44, 0x36, 0x53, 0x9d, 0x71, 0x00, 0xcd, 0x8f,
	0x54, 0xb0, 0x33, 0x9a, 0x24, 0x2c, 0x62, 0xb7, 0x99, 0xe5, 0x46, 0xce, 0xd0, 0x6b, 0x6f, 0xe8,
	0x3d, 0x82, 0xbd, 0x93, 0x30, 0xe4, 0x2c, 0xa4, 0x62, 0x12, 0x47, 0xe7, 0x6c, 0xe9, 0x57, 0x55,
	0xc7, 0x46, 0x56, 0xf6, 0x0d, 0xe3, 0x39, 0xbf, 0x61, 0xa3, 0x65, 0xc2, 0x2e, 0x25, 0x53, 0x4d,
	0xf7, 0x99, 0xd9, 0xdc, 0xaf, 0xba, 0xe9, 0x97, 0xee, 0x1a, 0x5c, 0xf9, 0x8e, 0x9e, 0xbf, 0x8a,
	0xf1, 0x3b, 0x70, 0xae, 0xf8, 0x24, 0xe6, 0x13, 0xb1, 0xf4, 0xdd, 0x36, 0xea, 0xec, 0xf5, 0x9e,
	0xcb, 0x0f, 0x33, 0x33, 0x42, 0xff, 0xae, 0x1a, 0x48, 0xde, 0x8a, 0x5f, 0x82, 0x2d, 0x47, 0xfa,
	0xa0, 0x20, 0x4f, 0x8b, 0x90, 0x93, 0x29, 0xe3, 0x42, 0x16, 0x89, 0x6a, 0x09, 0x0e, 0x61, 0xd7,
	0x60, 0xc1, 0x00, 0xb5, 0xcb, 0x98, 0xcf, 0xe8, 0xd4, 0xdb, 0xc1, 0x75, 0xb0, 0x3e, 0xc5, 0x0b,
	0x0f, 0x05, 0xc7, 0xe0, 0xe6, 0x40, 0xec, 0x80, 0x3d, 0x88, 0xbe, 0xc4, 0xde, 0x0e, 0x6e, 0x40,
	0xfd, 0x33, 0xe5, 0xd1, 0x24, 0x0a, 0x3d, 0x84, 0x5d, 0xa8, 0xf6, 0x39, 0x8f, 0xb9, 0x57, 0x91,
	0xf9, 0xe1, 0xfc, 0xe6, 0x86, 0xa5, 0xa9, 0x67, 0x8d, 0x6b, 0xea, 0x7f, 0xf8, 0xcd, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x08, 0x18, 0x8e, 0x08, 0x9c, 0x07, 0x00, 0x00,
}
