// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/remote_write.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PromWriteRequest struct {
	Timeseries           []*PromTimeSeries `protobuf:"bytes,1,rep,name=timeseries,proto3" json:"timeseries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PromWriteRequest) Reset()         { *m = PromWriteRequest{} }
func (m *PromWriteRequest) String() string { return proto.CompactTextString(m) }
func (*PromWriteRequest) ProtoMessage()    {}
func (*PromWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8825d3f466a1ddf3, []int{0}
}

func (m *PromWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromWriteRequest.Unmarshal(m, b)
}
func (m *PromWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromWriteRequest.Marshal(b, m, deterministic)
}
func (m *PromWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromWriteRequest.Merge(m, src)
}
func (m *PromWriteRequest) XXX_Size() int {
	return xxx_messageInfo_PromWriteRequest.Size(m)
}
func (m *PromWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromWriteRequest proto.InternalMessageInfo

func (m *PromWriteRequest) GetTimeseries() []*PromTimeSeries {
	if m != nil {
		return m.Timeseries
	}
	return nil
}

type PromTimeSeries struct {
	Labels               []*PromLabel  `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Samples              []*PromSample `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PromTimeSeries) Reset()         { *m = PromTimeSeries{} }
func (m *PromTimeSeries) String() string { return proto.CompactTextString(m) }
func (*PromTimeSeries) ProtoMessage()    {}
func (*PromTimeSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_8825d3f466a1ddf3, []int{1}
}

func (m *PromTimeSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromTimeSeries.Unmarshal(m, b)
}
func (m *PromTimeSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromTimeSeries.Marshal(b, m, deterministic)
}
func (m *PromTimeSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromTimeSeries.Merge(m, src)
}
func (m *PromTimeSeries) XXX_Size() int {
	return xxx_messageInfo_PromTimeSeries.Size(m)
}
func (m *PromTimeSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_PromTimeSeries.DiscardUnknown(m)
}

var xxx_messageInfo_PromTimeSeries proto.InternalMessageInfo

func (m *PromTimeSeries) GetLabels() []*PromLabel {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PromTimeSeries) GetSamples() []*PromSample {
	if m != nil {
		return m.Samples
	}
	return nil
}

type PromLabel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromLabel) Reset()         { *m = PromLabel{} }
func (m *PromLabel) String() string { return proto.CompactTextString(m) }
func (*PromLabel) ProtoMessage()    {}
func (*PromLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_8825d3f466a1ddf3, []int{2}
}

func (m *PromLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromLabel.Unmarshal(m, b)
}
func (m *PromLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromLabel.Marshal(b, m, deterministic)
}
func (m *PromLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromLabel.Merge(m, src)
}
func (m *PromLabel) XXX_Size() int {
	return xxx_messageInfo_PromLabel.Size(m)
}
func (m *PromLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_PromLabel.DiscardUnknown(m)
}

var xxx_messageInfo_PromLabel proto.InternalMessageInfo

func (m *PromLabel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PromLabel) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PromSample struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromSample) Reset()         { *m = PromSample{} }
func (m *PromSample) String() string { return proto.CompactTextString(m) }
func (*PromSample) ProtoMessage()    {}
func (*PromSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_8825d3f466a1ddf3, []int{3}
}

func (m *PromSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromSample.Unmarshal(m, b)
}
func (m *PromSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromSample.Marshal(b, m, deterministic)
}
func (m *PromSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromSample.Merge(m, src)
}
func (m *PromSample) XXX_Size() int {
	return xxx_messageInfo_PromSample.Size(m)
}
func (m *PromSample) XXX_DiscardUnknown() {
	xxx_messageInfo_PromSample.DiscardUnknown(m)
}

var xxx_messageInfo_PromSample proto.InternalMessageInfo

func (m *PromSample) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PromSample) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*PromWriteRequest)(nil), "pb.PromWriteRequest")
	proto.RegisterType((*PromTimeSeries)(nil), "pb.PromTimeSeries")
	proto.RegisterType((*PromLabel)(nil), "pb.PromLabel")
	proto.RegisterType((*PromSample)(nil), "pb.PromSample")
}

func init() { proto.RegisterFile("pb/remote_write.proto", fileDescriptor_8825d3f466a1ddf3) }

var fileDescriptor_8825d3f466a1ddf3 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0xd9, 0x1f, 0x9e, 0xb7, 0x23, 0x1e, 0xcb, 0xa0, 0xb0, 0x85, 0xc5, 0xb1, 0x20, 0x6c,
	0xb5, 0xc2, 0x89, 0xbd, 0xf5, 0x61, 0x21, 0x39, 0xc1, 0x52, 0x12, 0x98, 0x22, 0x90, 0x98, 0x98,
	0xe4, 0xf4, 0xdf, 0x97, 0x8c, 0x17, 0x57, 0xbb, 0xe4, 0x7b, 0xdf, 0x7b, 0x90, 0xc0, 0xb5, 0x57,
	0x77, 0x81, 0xac, 0x4b, 0xf4, 0xf6, 0x15, 0x74, 0xa2, 0xd9, 0x07, 0x97, 0x1c, 0xd6, 0x5e, 0x8d,
	0x02, 0xfa, 0xe7, 0xe0, 0xec, 0x6b, 0xc6, 0x82, 0x3e, 0x8e, 0x14, 0x13, 0xee, 0x00, 0x92, 0xb6,
	0x14, 0x29, 0x68, 0x8a, 0x43, 0xb5, 0x6d, 0xa6, 0x8b, 0x1d, 0xce, 0x5e, 0xcd, 0xd9, 0x7c, 0xd1,
	0x96, 0x0e, 0x9c, 0x88, 0x3f, 0xd6, 0xbe, 0x5d, 0xd7, 0x7d, 0xb3, 0x6f, 0xd7, 0x4d, 0xdf, 0x8e,
	0x12, 0x36, 0xff, 0x4d, 0xbc, 0x85, 0x95, 0x91, 0x8a, 0x4c, 0x59, 0xbb, 0x2c, 0x6b, 0x4f, 0x99,
	0x8a, 0x53, 0x88, 0x13, 0x9c, 0x47, 0x69, 0xbd, 0xa1, 0x38, 0xd4, 0xec, 0x6d, 0x8a, 0x77, 0x60,
	0x2c, 0x4a, 0x3c, 0x3e, 0x40, 0xf7, 0x5b, 0x47, 0x84, 0xf6, 0x5d, 0x5a, 0x1a, 0xaa, 0x6d, 0x35,
	0x75, 0x82, 0xcf, 0x78, 0x05, 0x67, 0x9f, 0xd2, 0x1c, 0x69, 0xa8, 0x19, 0xfe, 0x5c, 0xc6, 0x47,
	0x80, 0x65, 0x6d, 0x71, 0x72, 0xb1, 0x3a, 0x39, 0x78, 0x03, 0x1d, 0xbf, 0x2b, 0x49, 0xeb, 0xb9,
	0xdd, 0x88, 0x05, 0xa8, 0x15, 0x7f, 0xdd, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x3f,
	0xa6, 0x14, 0x53, 0x01, 0x00, 0x00,
}
